### ISSUE TITLE
10/01 デプロイ失敗

### ISSUE THREAD

**Issue by Fendo181** [Fendo181/FlexTimeCheck#5]
本番環境へのデプロイに失敗した。

```
Autoprefixer doesn’t support Node v4.2.6. Update it.
```

[Autoprefixe](https://github.com/postcss/autoprefixer)は`node  v4.2.6`をサポートしてないのが原因みたい 🤔 

<details>

```sh
remote: Download Yarn at https://yarnpkg.com/en/docs/install
remote: I, [2018-10-01T02:18:27.437312 #77]  INFO -- : Writing /tmp/d20181001-24-1c01pdl/public/assets/application-44d2501fbc4bfe5ce5a57b2238d7e4a1522740a0d9b49684e0dfebb4e5507e81.js
remote: I, [2018-10-01T02:18:27.444964 #77]  INFO -- : Writing /tmp/d20181001-24-1c01pdl/public/assets/application-44d2501fbc4bfe5ce5a57b2238d7e4a1522740a0d9b49684e0dfebb4e5507e81.js.gz
remote: rails aborted!
remote: Autoprefixer doesn’t support Node v4.2.6. Update it.
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/processor.rb:163:in `runtime'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/processor.rb:37:in `process'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/sprockets.rb:20:in `run'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/sprockets.rb:14:in `call'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:46:in `invoke'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
remote: /tmp/d20181001-24-1c01pdl/bin/rails:9:in `require'
remote: /tmp/d20181001-24-1c01pdl/bin/rails:9:in `<top (required)>'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
remote: /var/app/shared/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
remote: /tmp/d20181001-24-1c01pdl/bin/spring:15:in `<top (required)>'
remote: bin/rails:3:in `load'
remote: bin/rails:3:in `<main>'
remote: Tasks: TOP => assets:precompile
remote: (See full trace by running task with --trace)
remote: Build seems to be failed. Abort
```

</details>

**Comment by Fendo181** [comment]
これ見て、`mini_racer`を追加して対処するようにしたら、デプロイできました!   😇 

383ef8a9c1d3680eb5eafdc46f268d52de6691b6

[【Rails5】Autoprefixer doesn’t support Node v4.8.2. というエラーへの対処法 - logicoffee プログラミング勉強日記](https://logicoffee.hatenablog.com/entry/2018/09/01/200627)
